### ISSUE TITLE
Passing configuration to Redis via environment variable in Docker Compose crashes Redis

### ISSUE THREAD

**Issue by simonprickett** [redis-stack/redis-stack#110]
It seems that passing any sort of configuration to Redis via `REDIS_ARGS` when using Docker Compose crashes Redis.

Example `docker-compose.yml` attempt to configure keyspace notifications:

```yaml
version: "3.9"
services:
  redis:
    container_name: redis_keyspace_events_node_demo
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS="--notify-keyspace-events Ksg"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```

and example with no configuration set but passing in the environment variable anyway:

```yaml
version: "3.9"
services:
  redis:
    container_name: redis_keyspace_events_node_demo
    image: "redis/redis-stack:latest"
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      - REDIS_ARGS=""
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
```

What happens in both cases is that the Redis server fails to start, with a RedisBloom issue:

```bash
$ docker-compose up
Creating network "keyspace-notifications-node-redis_default" with the default driver
Creating redis_keyspace_events_node_demo ... done
Attaching to redis_keyspace_events_node_demo
redis_keyspace_events_node_demo | 9:C 04 May 2022 12:13:20.523 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_keyspace_events_node_demo | 9:C 04 May 2022 12:13:20.523 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=9, just started
redis_keyspace_events_node_demo | 9:C 04 May 2022 12:13:20.523 # Configuration loaded
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.523 * monotonic clock: POSIX clock_gettime
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.524 * Running mode=standalone, port=6379.
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.524 # Server initialized
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.524 * <search> Redis version found by RedisSearch : 6.2.6 - oss
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * <search> RediSearch version 2.2.10 (Git=HEAD-3d0701f6)
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * <search> Low level api version 1 initialized successfully
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8,
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * <search> Initialized thread pool!
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * <search> Enabled diskless replication
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.525 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.527 * <graph> Starting up RedisGraph version 2.8.9.
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.528 * <graph> Thread pool created, using 8 threads.
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.528 * <graph> Maximum number of OpenMP threads set to 8
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.528 * Module 'graph' loaded from /opt/redis-stack/lib/redisgraph.so
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.529 * <timeseries> RedisTimeSeries version 10609, git_sha=f36e5a703dc9a2487880087a34f6cb0e56d9a459
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.529 * <timeseries> Redis version found by RedisTimeSeries : 6.2.6 - oss
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.529 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.529 * <timeseries> loaded server DUPLICATE_POLICY: block
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.529 * <timeseries> Setting default series ENCODING to: compressed
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <timeseries> Detected redis oss
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <timeseries> Enabled diskless replication
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <ReJSON> version: 20007 git sha: e51b585 branch: HEAD
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <ReJSON> Exported RedisJSON_V1 API
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <ReJSON> Enabled diskless replication
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <ReJSON> Created new data type 'ReJSON-RL'
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <search> Acquired RedisJSON_V1 API
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 * <graph> Acquired RedisJSON_V1 API
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 # <bf> Unrecognized option
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 # Module /opt/redis-stack/lib/redisbloom.so initialization failed. Module not loaded
redis_keyspace_events_node_demo | 9:M 04 May 2022 12:13:20.530 # Can't load module from /opt/redis-stack/lib/redisbloom.so: server aborting
```

Removing the `environment` section from `docker-compose.yml` means the server starts, but prevents me from passing configuration into Redis.

I am using mac OS 12.3.1 and Docker desktop as follows:

```bash
$ docker --version
Docker version 20.10.12, build e91ed57
```

**Comment by chayim** [comment]
Thanks @simonprickett I've got a unit test now that reproduces this consistently.

**Comment by jscott3201** [comment]
```
version: '3.9'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: 'redis-stack'
    volumes:
      - /opt/redis_data:/data
    environment:
      - REDISTIMESERIES_ARGS=DUPLICATE_POLICY LAST RETENTION_POLICY 604800000
```

Anyone coming here should take note that when doing this in compose at minimum you can't wrap the environment variables in quotes and should set them up like so. You will notice the logs for time-series in this case output your settings:

```
<timeseries> RedisTimeSeries version 10617, git_sha=c32b0cb0d8ebc1d31b74c624b8b0424628ff7887
<timeseries> Redis version found by RedisTimeSeries : 7.0.4 - oss
<timeseries> loaded default retention policy: 604800000
<timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
<timeseries> loaded server DUPLICATE_POLICY: last
<timeseries> Setting default series ENCODING to: compressed
<timeseries> Detected redis oss
Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
```
