### ISSUE TITLE
persistent volume

### ISSUE THREAD

**Issue by mariushosting** [redis-stack/redis-stack#210]
is /data the persistent volume ?

**Comment by ThomasJRyan** [comment]
To add onto this, I'm spinning up the stack with `docker-compose` and while admittedly I'm not very good with Docker in general, it seems no matter what I do the data won't persist.

My `docker-compose.yml` looks like this:
```yaml
version: '3.7'

services:
  redis_server:
    image: redis/redis-stack:latest
    volumes:
      - type: volume
        source: redis_volume
        target: /data

volumes:
  redis_volume:
```
I'm not certain what to do to get my data to persist

**Comment by xsolinsx** [comment]
+1
I have the same problem, no persistence at all
the following is my docker-compose (driver local-persist is a [custom plugin](https://github.com/MatchbookLab/local-persist) that is working for all my other services, so that should not be a problem)
```yaml
version: "3"

services:
  redis:
    container_name: redis
    image: redis/redis-stack:latest
    restart: always
    environment:
      REDIS_ARGS: "--requirepass test_pwd"
    volumes:
      - redis_data:/data:rw

volumes:
  redis_data:
    name: redis_data
    driver: local-persist
    driver_opts:
      mountpoint: /home/erics/projects/redis/data
```
bonus: it would be nice to be able to use docker secrets like other projects do (e.g. [nextcloud](https://github.com/docker-library/docs/blob/master/nextcloud/README.md#docker-secrets) for the "basic" feature and [authelia](https://www.authelia.com/integration/deployment/docker/#using-a-secrets-volume) for the volume variant)

**Comment by remiconnesson** [comment]
Same here with the follow docker compose, as per the documentation just declaring a volume should be enough but it's not.

I've tried passing `--append-only yes` though `REDIS_ARGS="..."` without success (it crashes` redis-stack`)

This is my working docker-compose file, despite the volume it doesn't persis.

```yaml
services:
  web:
    build: ./code
    ports:
      - "8000:80"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_volume:/data

volumes:            
  redis_volume: {}
```
