### ISSUE TITLE
Unable to override redis "dir" configuration

### ISSUE THREAD

**Issue by georgejdli** [redis-stack/redis-stack#298]
I'm moving from redis-server to redis-stack-server. 

I'm using the docker image tag redis/redis-stack:latest

In my previous configuration for redis-server I have snapshotting enabled with my own custom directory for the database file

redis.conf file:
```conf
dir /redis-snapshot
save 600 1
save 300 5
```

I tried to same configuration for redis-stack-server but the "dir" value remains the default of "/var/lib/redis-stack":
```shell
127.0.0.1:6380> config get dir
1) "dir"
2) "/var/lib/redis-stack"
```

Is there a way to override the "dir" value? I also tried setting the env variable REDIS_ARGS="dir /redis-snapshot" before starting the server but that didn't work either.

**Comment by georgejdli** [comment]
Ok so I misunderstood a few things:

- In my kubernetes deployment I was overriding the docker entrypoint.sh script and calling the redis-stack-server startup script so I could use my custom config file. That's why the default "dir" value was set to /var/lib/redis-stack (see: [redis-stack-server script](https://github.com/redis-stack/redis-stack/blob/6.2.4/etc/scripts/redis-stack-server)


- Once I got rid of that I was able to use my custom config file by mounting a configMap to the path /redis-stack.conf (checking  [the entrypoint.sh script](https://github.com/redis-stack/redis-stack/blob/6.2.4/etc/scripts/entrypoint.sh)
```yaml
volumeMounts:
# redis-stack entrypoint.sh docker script will look for this path to load the config file
- mountPath: /redis-stack.conf
   name: config
   subPath: redis-stack.conf
```
- Then I was able to override the "dir" config prop with the REDIS_DATA_DIR environment variable
```yaml
env:
# where the db snapshots will be stored (and reloaded from on pod restart)
- name: REDIS_DATA_DIR
   value: {{ .Values.redis.dataDir }}
```

Is overriding the REDIS_DATA_DIR environment variable the preferred way to set the "dir" prop? Maybe that could be added to the docs?
