### ISSUE TITLE
Docker container of image 'redis/redis-stack:latest' does not perform a DB DISK save on SHUTDOWN

### ISSUE THREAD

**Issue by wuarmin** [redis-stack/redis-stack#371]
Hey,

I have following `redis-stack`-container:

```yml
  store:
    image: redis/redis-stack:latest
    restart: unless-stopped
    volumes:
      - ./storage/redis-stack-data/:/data
```

`SAVE` is configured properly and works:

```txt
user@026d54473ab5:/# redis-cli 
127.0.0.1:6379> CONFIG GET SAVE
1) "save"
2) "3600 1 300 100 60 10000"
127.0.0.1:6379> SAVE
OK
```
```txt
8:M 30 Mar 2023 08:42:05.999 * Ready to accept connections
8:M 30 Mar 2023 08:43:16.067 * DB saved on disk
```

But when I shutdown the container:
```txt
8:M 30 Mar 2023 08:43:16.067 * DB saved on disk
8:signal-handler (1680166043) Received SIGTERM scheduling shutdown...
8:signal-handler (1680166043) Received SIGTERM scheduling shutdown...
```
No DB DISK save take place.

what am I doing wrong?

thanks
