### ISSUE TITLE
How to change redis.conf with docker-compose?

### ISSUE THREAD

**Issue by dj-fiorex** [redis-stack/redis-stack#373]
Hello to all, i'm using redis-stack-server with other container with a docker-compose:
```

version: '3'

services:
  vs-admin:
    image: medelba/vs-admin:0.9
    ports:
      - '3000:3000'
    environment:
      - VIRTUAL_HOST=vaso-smart.current-project.dev
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=vaso-smart.current-project.dev
      - VIRTUAL_PATH=/
    depends_on:
      - vs-backend
      - redis
    env_file:
      - stack.env
  vs-backend:
    image: medelba/vs-backend:0.9
    ports:
      - '8081:8081'
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=vaso-smart.current-project.dev
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=vaso-smart.current-project.dev
      - VIRTUAL_PATH=/api
    env_file:
      - stack.env
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - '6379:6379'
    env_file:
      - stack.env
    volumes:
      - redis-data:/data
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - '/etc/nginx/certs'

  nginx-proxy-acme:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=carmelofiorello@gmail.com
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - acme:/etc/acme.sh
    volumes_from:
      - 'nginx-proxy'

volumes:
  acme:
  redis-data:

```
I would like to change the content of redis.conf to be able to bind only on localhost for security reason, but i don't know how to change the redis.conf with docker-compose withouth mounting a local folder because the deployment will be headless.

Is there a way? 
Thanks!

EDIT:

i saw that redis-stack-server uses another conf file /etc/redis-stack.conf do i need to override this? if yes, how? i tried to change that file inside my docker container and then restart the container but it seems not to accept `bind 127.0.0.1 -::1`
What am i doing wrong?
Thanks!
