### ISSUE TITLE
The dir command of in redis-stack-server .conf  is misleading.

### ISSUE THREAD

**Issue by daimalou** [redis-stack/redis-stack#597]
Thank you for develop `redis-stack-server`,

I spent an entire afternoon solving this dir problem.

Here is my conf
```
# This not work in redis-stack-server
dir /data

save 1 1
save 300 10
save 60 10000
dbfilename dump.rdb

appendonly yes
appendfilename "appendonly.aof"
appendfsync always
protected-mode no
```
Scenario One(Not work):
```
services:
  redis-stack-server:
    image: redis/redis-stack-server:latest 
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-stack-server", "/usr/local/etc/redis/redis.conf"]

```

Scenario Two(Not work):
```
services:
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: cache
    ports:
      - "6379:6379" 
    volumes:
      - ./redis/data:/data  
      - ./redis/redis-stack-server.conf:/usr/local/etc/redis/redis-stack-server.conf 
    environment:
      - REDIS_ARGS=--dir /data
    command: [
        "redis-stack-server", "/usr/local/etc/redis/redis-stack-server.conf"] 
```

Work example:
```Dockerfile
services:
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: core-redis-stack-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/redis-stack-server.conf:/usr/local/etc/redis/redis-stack-server.conf
    command: [
        "redis-stack-server",
        "/usr/local/etc/redis/redis-stack-server.conf",
        "--dir",
        "/data",
      ] # work even not set dir in conf
```

Cant find any instruction in .
https://redis.io/docs/latest/operate/oss_and_stack/management/config-file/
https://hub.docker.com/r/redis/redis-stack-server
https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/

it's a bug or?
